package com.school_circle.ssm.model;

import java.util.Date;

public class ScLogin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_login.id
     *
     * @mbggenerated Thu May 04 14:20:52 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_login.user_id
     *
     * @mbggenerated Thu May 04 14:20:52 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_login.token
     *
     * @mbggenerated Thu May 04 14:20:52 CST 2017
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_login.update_time
     *
     * @mbggenerated Thu May 04 14:20:52 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_login.id
     *
     * @return the value of sc_login.id
     *
     * @mbggenerated Thu May 04 14:20:52 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_login.id
     *
     * @param id the value for sc_login.id
     *
     * @mbggenerated Thu May 04 14:20:52 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_login.user_id
     *
     * @return the value of sc_login.user_id
     *
     * @mbggenerated Thu May 04 14:20:52 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_login.user_id
     *
     * @param userId the value for sc_login.user_id
     *
     * @mbggenerated Thu May 04 14:20:52 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_login.token
     *
     * @return the value of sc_login.token
     *
     * @mbggenerated Thu May 04 14:20:52 CST 2017
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_login.token
     *
     * @param token the value for sc_login.token
     *
     * @mbggenerated Thu May 04 14:20:52 CST 2017
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_login.update_time
     *
     * @return the value of sc_login.update_time
     *
     * @mbggenerated Thu May 04 14:20:52 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_login.update_time
     *
     * @param updateTime the value for sc_login.update_time
     *
     * @mbggenerated Thu May 04 14:20:52 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}