package com.school_circle.ssm.model;

import java.util.Date;

public class ScMultipartFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_multipart_file.multipart_id
     *
     * @mbggenerated Wed Apr 26 15:21:13 CST 2017
     */
    private String multipartId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_multipart_file.multipart_type
     *
     * @mbggenerated Wed Apr 26 15:21:13 CST 2017
     */
    private Byte multipartType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_multipart_file.multipart_from
     *
     * @mbggenerated Wed Apr 26 15:21:13 CST 2017
     */
    private Byte multipartFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_multipart_file.create_on
     *
     * @mbggenerated Wed Apr 26 15:21:13 CST 2017
     */
    private Date createOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_multipart_file.relation_id
     *
     * @mbggenerated Wed Apr 26 15:21:13 CST 2017
     */
    private String relationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_multipart_file.multipart_id
     *
     * @return the value of sc_multipart_file.multipart_id
     *
     * @mbggenerated Wed Apr 26 15:21:13 CST 2017
     */
    public String getMultipartId() {
        return multipartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_multipart_file.multipart_id
     *
     * @param multipartId the value for sc_multipart_file.multipart_id
     *
     * @mbggenerated Wed Apr 26 15:21:13 CST 2017
     */
    public void setMultipartId(String multipartId) {
        this.multipartId = multipartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_multipart_file.multipart_type
     *
     * @return the value of sc_multipart_file.multipart_type
     *
     * @mbggenerated Wed Apr 26 15:21:13 CST 2017
     */
    public Byte getMultipartType() {
        return multipartType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_multipart_file.multipart_type
     *
     * @param multipartType the value for sc_multipart_file.multipart_type
     *
     * @mbggenerated Wed Apr 26 15:21:13 CST 2017
     */
    public void setMultipartType(Byte multipartType) {
        this.multipartType = multipartType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_multipart_file.multipart_from
     *
     * @return the value of sc_multipart_file.multipart_from
     *
     * @mbggenerated Wed Apr 26 15:21:13 CST 2017
     */
    public Byte getMultipartFrom() {
        return multipartFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_multipart_file.multipart_from
     *
     * @param multipartFrom the value for sc_multipart_file.multipart_from
     *
     * @mbggenerated Wed Apr 26 15:21:13 CST 2017
     */
    public void setMultipartFrom(Byte multipartFrom) {
        this.multipartFrom = multipartFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_multipart_file.create_on
     *
     * @return the value of sc_multipart_file.create_on
     *
     * @mbggenerated Wed Apr 26 15:21:13 CST 2017
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_multipart_file.create_on
     *
     * @param createOn the value for sc_multipart_file.create_on
     *
     * @mbggenerated Wed Apr 26 15:21:13 CST 2017
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_multipart_file.relation_id
     *
     * @return the value of sc_multipart_file.relation_id
     *
     * @mbggenerated Wed Apr 26 15:21:13 CST 2017
     */
    public String getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_multipart_file.relation_id
     *
     * @param relationId the value for sc_multipart_file.relation_id
     *
     * @mbggenerated Wed Apr 26 15:21:13 CST 2017
     */
    public void setRelationId(String relationId) {
        this.relationId = relationId;
    }
}