package com.school_circle.ssm.model;

import java.util.Date;

public class ScPost {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_post.id
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_post.title
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_post.author_id
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    private Long authorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_post.thumbnail
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    private String thumbnail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_post.post_type
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    private String postType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_post.like_count
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    private Long likeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_post.reply_count
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    private Long replyCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_post.view_count
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    private Long viewCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_post.interest_count
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    private Long interestCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_post.create_on
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    private Date createOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_post.cotent
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    private String cotent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_post.id
     *
     * @return the value of sc_post.id
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_post.id
     *
     * @param id the value for sc_post.id
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_post.title
     *
     * @return the value of sc_post.title
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_post.title
     *
     * @param title the value for sc_post.title
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_post.author_id
     *
     * @return the value of sc_post.author_id
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    public Long getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_post.author_id
     *
     * @param authorId the value for sc_post.author_id
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    public void setAuthorId(Long authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_post.thumbnail
     *
     * @return the value of sc_post.thumbnail
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    public String getThumbnail() {
        return thumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_post.thumbnail
     *
     * @param thumbnail the value for sc_post.thumbnail
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_post.post_type
     *
     * @return the value of sc_post.post_type
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    public String getPostType() {
        return postType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_post.post_type
     *
     * @param postType the value for sc_post.post_type
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    public void setPostType(String postType) {
        this.postType = postType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_post.like_count
     *
     * @return the value of sc_post.like_count
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    public Long getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_post.like_count
     *
     * @param likeCount the value for sc_post.like_count
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    public void setLikeCount(Long likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_post.reply_count
     *
     * @return the value of sc_post.reply_count
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    public Long getReplyCount() {
        return replyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_post.reply_count
     *
     * @param replyCount the value for sc_post.reply_count
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    public void setReplyCount(Long replyCount) {
        this.replyCount = replyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_post.view_count
     *
     * @return the value of sc_post.view_count
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    public Long getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_post.view_count
     *
     * @param viewCount the value for sc_post.view_count
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    public void setViewCount(Long viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_post.interest_count
     *
     * @return the value of sc_post.interest_count
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    public Long getInterestCount() {
        return interestCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_post.interest_count
     *
     * @param interestCount the value for sc_post.interest_count
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    public void setInterestCount(Long interestCount) {
        this.interestCount = interestCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_post.create_on
     *
     * @return the value of sc_post.create_on
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_post.create_on
     *
     * @param createOn the value for sc_post.create_on
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_post.cotent
     *
     * @return the value of sc_post.cotent
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    public String getCotent() {
        return cotent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_post.cotent
     *
     * @param cotent the value for sc_post.cotent
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    public void setCotent(String cotent) {
        this.cotent = cotent;
    }
}