package com.school_circle.ssm.model;

import java.util.Date;

public class ScReply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_reply.id
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_reply.author_id
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    private Long authorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_reply.post_type
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    private Byte postType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_reply.like_count
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    private Long likeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_reply.reply_count
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    private Long replyCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_reply.interest_count
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    private Long interestCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_reply.parent_post_id
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    private String parentPostId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_reply.reply_to
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    private Long replyTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_reply.root_post_id
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    private String rootPostId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_reply.create_on
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    private Date createOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_reply.cotent
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    private String cotent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_reply.id
     *
     * @return the value of sc_reply.id
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_reply.id
     *
     * @param id the value for sc_reply.id
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_reply.author_id
     *
     * @return the value of sc_reply.author_id
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    public Long getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_reply.author_id
     *
     * @param authorId the value for sc_reply.author_id
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    public void setAuthorId(Long authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_reply.post_type
     *
     * @return the value of sc_reply.post_type
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    public Byte getPostType() {
        return postType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_reply.post_type
     *
     * @param postType the value for sc_reply.post_type
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    public void setPostType(Byte postType) {
        this.postType = postType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_reply.like_count
     *
     * @return the value of sc_reply.like_count
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    public Long getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_reply.like_count
     *
     * @param likeCount the value for sc_reply.like_count
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    public void setLikeCount(Long likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_reply.reply_count
     *
     * @return the value of sc_reply.reply_count
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    public Long getReplyCount() {
        return replyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_reply.reply_count
     *
     * @param replyCount the value for sc_reply.reply_count
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    public void setReplyCount(Long replyCount) {
        this.replyCount = replyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_reply.interest_count
     *
     * @return the value of sc_reply.interest_count
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    public Long getInterestCount() {
        return interestCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_reply.interest_count
     *
     * @param interestCount the value for sc_reply.interest_count
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    public void setInterestCount(Long interestCount) {
        this.interestCount = interestCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_reply.parent_post_id
     *
     * @return the value of sc_reply.parent_post_id
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    public String getParentPostId() {
        return parentPostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_reply.parent_post_id
     *
     * @param parentPostId the value for sc_reply.parent_post_id
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    public void setParentPostId(String parentPostId) {
        this.parentPostId = parentPostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_reply.reply_to
     *
     * @return the value of sc_reply.reply_to
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    public Long getReplyTo() {
        return replyTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_reply.reply_to
     *
     * @param replyTo the value for sc_reply.reply_to
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    public void setReplyTo(Long replyTo) {
        this.replyTo = replyTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_reply.root_post_id
     *
     * @return the value of sc_reply.root_post_id
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    public String getRootPostId() {
        return rootPostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_reply.root_post_id
     *
     * @param rootPostId the value for sc_reply.root_post_id
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    public void setRootPostId(String rootPostId) {
        this.rootPostId = rootPostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_reply.create_on
     *
     * @return the value of sc_reply.create_on
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_reply.create_on
     *
     * @param createOn the value for sc_reply.create_on
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_reply.cotent
     *
     * @return the value of sc_reply.cotent
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    public String getCotent() {
        return cotent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_reply.cotent
     *
     * @param cotent the value for sc_reply.cotent
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    public void setCotent(String cotent) {
        this.cotent = cotent;
    }
}