package com.school_circle.ssm.model;

import java.util.Date;

public class ScUserFriend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_friend.id
     *
     * @mbggenerated Fri Mar 24 16:55:15 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_friend.user_id
     *
     * @mbggenerated Fri Mar 24 16:55:15 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_friend.friend_id
     *
     * @mbggenerated Fri Mar 24 16:55:15 CST 2017
     */
    private Long friendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_friend.status
     *
     * @mbggenerated Fri Mar 24 16:55:15 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_friend.add_time
     *
     * @mbggenerated Fri Mar 24 16:55:15 CST 2017
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_friend.update_time
     *
     * @mbggenerated Fri Mar 24 16:55:15 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_friend.remark
     *
     * @mbggenerated Fri Mar 24 16:55:15 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_friend.group_id
     *
     * @mbggenerated Fri Mar 24 16:55:15 CST 2017
     */
    private Long groupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_friend.id
     *
     * @return the value of sc_user_friend.id
     *
     * @mbggenerated Fri Mar 24 16:55:15 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_friend.id
     *
     * @param id the value for sc_user_friend.id
     *
     * @mbggenerated Fri Mar 24 16:55:15 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_friend.user_id
     *
     * @return the value of sc_user_friend.user_id
     *
     * @mbggenerated Fri Mar 24 16:55:15 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_friend.user_id
     *
     * @param userId the value for sc_user_friend.user_id
     *
     * @mbggenerated Fri Mar 24 16:55:15 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_friend.friend_id
     *
     * @return the value of sc_user_friend.friend_id
     *
     * @mbggenerated Fri Mar 24 16:55:15 CST 2017
     */
    public Long getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_friend.friend_id
     *
     * @param friendId the value for sc_user_friend.friend_id
     *
     * @mbggenerated Fri Mar 24 16:55:15 CST 2017
     */
    public void setFriendId(Long friendId) {
        this.friendId = friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_friend.status
     *
     * @return the value of sc_user_friend.status
     *
     * @mbggenerated Fri Mar 24 16:55:15 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_friend.status
     *
     * @param status the value for sc_user_friend.status
     *
     * @mbggenerated Fri Mar 24 16:55:15 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_friend.add_time
     *
     * @return the value of sc_user_friend.add_time
     *
     * @mbggenerated Fri Mar 24 16:55:15 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_friend.add_time
     *
     * @param addTime the value for sc_user_friend.add_time
     *
     * @mbggenerated Fri Mar 24 16:55:15 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_friend.update_time
     *
     * @return the value of sc_user_friend.update_time
     *
     * @mbggenerated Fri Mar 24 16:55:15 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_friend.update_time
     *
     * @param updateTime the value for sc_user_friend.update_time
     *
     * @mbggenerated Fri Mar 24 16:55:15 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_friend.remark
     *
     * @return the value of sc_user_friend.remark
     *
     * @mbggenerated Fri Mar 24 16:55:15 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_friend.remark
     *
     * @param remark the value for sc_user_friend.remark
     *
     * @mbggenerated Fri Mar 24 16:55:15 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_friend.group_id
     *
     * @return the value of sc_user_friend.group_id
     *
     * @mbggenerated Fri Mar 24 16:55:15 CST 2017
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_friend.group_id
     *
     * @param groupId the value for sc_user_friend.group_id
     *
     * @mbggenerated Fri Mar 24 16:55:15 CST 2017
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

}