package com.school_circle.ssm.model;

public class ScUserFriendGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_friend_group.id
     *
     * @mbggenerated Mon Apr 24 15:16:38 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_friend_group.user_id
     *
     * @mbggenerated Mon Apr 24 15:16:38 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_friend_group.group_name
     *
     * @mbggenerated Mon Apr 24 15:16:38 CST 2017
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_friend_group.group_number
     *
     * @mbggenerated Mon Apr 24 15:16:38 CST 2017
     */
    private Long groupNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_friend_group.id
     *
     * @return the value of sc_user_friend_group.id
     *
     * @mbggenerated Mon Apr 24 15:16:38 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_friend_group.id
     *
     * @param id the value for sc_user_friend_group.id
     *
     * @mbggenerated Mon Apr 24 15:16:38 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_friend_group.user_id
     *
     * @return the value of sc_user_friend_group.user_id
     *
     * @mbggenerated Mon Apr 24 15:16:38 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_friend_group.user_id
     *
     * @param userId the value for sc_user_friend_group.user_id
     *
     * @mbggenerated Mon Apr 24 15:16:38 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_friend_group.group_name
     *
     * @return the value of sc_user_friend_group.group_name
     *
     * @mbggenerated Mon Apr 24 15:16:38 CST 2017
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_friend_group.group_name
     *
     * @param groupName the value for sc_user_friend_group.group_name
     *
     * @mbggenerated Mon Apr 24 15:16:38 CST 2017
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_friend_group.group_number
     *
     * @return the value of sc_user_friend_group.group_number
     *
     * @mbggenerated Mon Apr 24 15:16:38 CST 2017
     */
    public Long getGroupNumber() {
        return groupNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_friend_group.group_number
     *
     * @param groupNumber the value for sc_user_friend_group.group_number
     *
     * @mbggenerated Mon Apr 24 15:16:38 CST 2017
     */
    public void setGroupNumber(Long groupNumber) {
        this.groupNumber = groupNumber;
    }
}