package com.school_circle.ssm.model;

public class ScUserUnreadMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_unread_message.id
     *
     * @mbggenerated Fri Mar 24 16:44:38 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_unread_message.user_id
     *
     * @mbggenerated Fri Mar 24 16:44:38 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_unread_message.from_id
     *
     * @mbggenerated Fri Mar 24 16:44:38 CST 2017
     */
    private Long fromId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_unread_message.message_count
     *
     * @mbggenerated Fri Mar 24 16:44:38 CST 2017
     */
    private Long messageCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_unread_message.id
     *
     * @return the value of sc_user_unread_message.id
     *
     * @mbggenerated Fri Mar 24 16:44:38 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_unread_message.id
     *
     * @param id the value for sc_user_unread_message.id
     *
     * @mbggenerated Fri Mar 24 16:44:38 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_unread_message.user_id
     *
     * @return the value of sc_user_unread_message.user_id
     *
     * @mbggenerated Fri Mar 24 16:44:38 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_unread_message.user_id
     *
     * @param userId the value for sc_user_unread_message.user_id
     *
     * @mbggenerated Fri Mar 24 16:44:38 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_unread_message.from_id
     *
     * @return the value of sc_user_unread_message.from_id
     *
     * @mbggenerated Fri Mar 24 16:44:38 CST 2017
     */
    public Long getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_unread_message.from_id
     *
     * @param fromId the value for sc_user_unread_message.from_id
     *
     * @mbggenerated Fri Mar 24 16:44:38 CST 2017
     */
    public void setFromId(Long fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_unread_message.message_count
     *
     * @return the value of sc_user_unread_message.message_count
     *
     * @mbggenerated Fri Mar 24 16:44:38 CST 2017
     */
    public Long getMessageCount() {
        return messageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_unread_message.message_count
     *
     * @param messageCount the value for sc_user_unread_message.message_count
     *
     * @mbggenerated Fri Mar 24 16:44:38 CST 2017
     */
    public void setMessageCount(Long messageCount) {
        this.messageCount = messageCount;
    }
}