package com.school_circle.ssm.model;

import java.util.Date;

public class ScUserSchoolData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_school_data.id
     *
     * @mbggenerated Mon Mar 13 15:29:39 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_school_data.school_name
     *
     * @mbggenerated Mon Mar 13 15:29:39 CST 2017
     */
    private String schoolName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_school_data.school_province
     *
     * @mbggenerated Mon Mar 13 15:29:39 CST 2017
     */
    private String schoolProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_school_data.school_city
     *
     * @mbggenerated Mon Mar 13 15:29:39 CST 2017
     */
    private String schoolCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_school_data.school_card_account
     *
     * @mbggenerated Mon Mar 13 15:29:39 CST 2017
     */
    private String schoolCardAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_school_data.school_card_password
     *
     * @mbggenerated Mon Mar 13 15:29:39 CST 2017
     */
    private String schoolCardPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_school_data.user_id
     *
     * @mbggenerated Mon Mar 13 15:29:39 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_school_data.create_on
     *
     * @mbggenerated Mon Mar 13 15:29:39 CST 2017
     */
    private Date createOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_school_data.id
     *
     * @return the value of sc_user_school_data.id
     *
     * @mbggenerated Mon Mar 13 15:29:39 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_school_data.id
     *
     * @param id the value for sc_user_school_data.id
     *
     * @mbggenerated Mon Mar 13 15:29:39 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_school_data.school_name
     *
     * @return the value of sc_user_school_data.school_name
     *
     * @mbggenerated Mon Mar 13 15:29:39 CST 2017
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_school_data.school_name
     *
     * @param schoolName the value for sc_user_school_data.school_name
     *
     * @mbggenerated Mon Mar 13 15:29:39 CST 2017
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_school_data.school_province
     *
     * @return the value of sc_user_school_data.school_province
     *
     * @mbggenerated Mon Mar 13 15:29:39 CST 2017
     */
    public String getSchoolProvince() {
        return schoolProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_school_data.school_province
     *
     * @param schoolProvince the value for sc_user_school_data.school_province
     *
     * @mbggenerated Mon Mar 13 15:29:39 CST 2017
     */
    public void setSchoolProvince(String schoolProvince) {
        this.schoolProvince = schoolProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_school_data.school_city
     *
     * @return the value of sc_user_school_data.school_city
     *
     * @mbggenerated Mon Mar 13 15:29:39 CST 2017
     */
    public String getSchoolCity() {
        return schoolCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_school_data.school_city
     *
     * @param schoolCity the value for sc_user_school_data.school_city
     *
     * @mbggenerated Mon Mar 13 15:29:39 CST 2017
     */
    public void setSchoolCity(String schoolCity) {
        this.schoolCity = schoolCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_school_data.school_card_account
     *
     * @return the value of sc_user_school_data.school_card_account
     *
     * @mbggenerated Mon Mar 13 15:29:39 CST 2017
     */
    public String getSchoolCardAccount() {
        return schoolCardAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_school_data.school_card_account
     *
     * @param schoolCardAccount the value for sc_user_school_data.school_card_account
     *
     * @mbggenerated Mon Mar 13 15:29:39 CST 2017
     */
    public void setSchoolCardAccount(String schoolCardAccount) {
        this.schoolCardAccount = schoolCardAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_school_data.school_card_password
     *
     * @return the value of sc_user_school_data.school_card_password
     *
     * @mbggenerated Mon Mar 13 15:29:39 CST 2017
     */
    public String getSchoolCardPassword() {
        return schoolCardPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_school_data.school_card_password
     *
     * @param schoolCardPassword the value for sc_user_school_data.school_card_password
     *
     * @mbggenerated Mon Mar 13 15:29:39 CST 2017
     */
    public void setSchoolCardPassword(String schoolCardPassword) {
        this.schoolCardPassword = schoolCardPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_school_data.user_id
     *
     * @return the value of sc_user_school_data.user_id
     *
     * @mbggenerated Mon Mar 13 15:29:39 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_school_data.user_id
     *
     * @param userId the value for sc_user_school_data.user_id
     *
     * @mbggenerated Mon Mar 13 15:29:39 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_school_data.create_on
     *
     * @return the value of sc_user_school_data.create_on
     *
     * @mbggenerated Mon Mar 13 15:29:39 CST 2017
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_school_data.create_on
     *
     * @param createOn the value for sc_user_school_data.create_on
     *
     * @mbggenerated Mon Mar 13 15:29:39 CST 2017
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }
}