package com.school_circle.ssm.model;

import java.util.Date;

public class ScUserMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_message.id
     *
     * @mbggenerated Fri Mar 24 16:44:25 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_message.from_user_id
     *
     * @mbggenerated Fri Mar 24 16:44:25 CST 2017
     */
    private Long fromUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_message.to_user_id
     *
     * @mbggenerated Fri Mar 24 16:44:25 CST 2017
     */
    private Long toUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_message.message_body
     *
     * @mbggenerated Fri Mar 24 16:44:25 CST 2017
     */
    private String messageBody;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_message.send_time
     *
     * @mbggenerated Fri Mar 24 16:44:25 CST 2017
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_user_message.accept_time
     *
     * @mbggenerated Fri Mar 24 16:44:25 CST 2017
     */
    private Date acceptTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_message.id
     *
     * @return the value of sc_user_message.id
     *
     * @mbggenerated Fri Mar 24 16:44:25 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_message.id
     *
     * @param id the value for sc_user_message.id
     *
     * @mbggenerated Fri Mar 24 16:44:25 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_message.from_user_id
     *
     * @return the value of sc_user_message.from_user_id
     *
     * @mbggenerated Fri Mar 24 16:44:25 CST 2017
     */
    public Long getFromUserId() {
        return fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_message.from_user_id
     *
     * @param fromUserId the value for sc_user_message.from_user_id
     *
     * @mbggenerated Fri Mar 24 16:44:25 CST 2017
     */
    public void setFromUserId(Long fromUserId) {
        this.fromUserId = fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_message.to_user_id
     *
     * @return the value of sc_user_message.to_user_id
     *
     * @mbggenerated Fri Mar 24 16:44:25 CST 2017
     */
    public Long getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_message.to_user_id
     *
     * @param toUserId the value for sc_user_message.to_user_id
     *
     * @mbggenerated Fri Mar 24 16:44:25 CST 2017
     */
    public void setToUserId(Long toUserId) {
        this.toUserId = toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_message.message_body
     *
     * @return the value of sc_user_message.message_body
     *
     * @mbggenerated Fri Mar 24 16:44:25 CST 2017
     */
    public String getMessageBody() {
        return messageBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_message.message_body
     *
     * @param messageBody the value for sc_user_message.message_body
     *
     * @mbggenerated Fri Mar 24 16:44:25 CST 2017
     */
    public void setMessageBody(String messageBody) {
        this.messageBody = messageBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_message.send_time
     *
     * @return the value of sc_user_message.send_time
     *
     * @mbggenerated Fri Mar 24 16:44:25 CST 2017
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_message.send_time
     *
     * @param sendTime the value for sc_user_message.send_time
     *
     * @mbggenerated Fri Mar 24 16:44:25 CST 2017
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_user_message.accept_time
     *
     * @return the value of sc_user_message.accept_time
     *
     * @mbggenerated Fri Mar 24 16:44:25 CST 2017
     */
    public Date getAcceptTime() {
        return acceptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_user_message.accept_time
     *
     * @param acceptTime the value for sc_user_message.accept_time
     *
     * @mbggenerated Fri Mar 24 16:44:25 CST 2017
     */
    public void setAcceptTime(Date acceptTime) {
        this.acceptTime = acceptTime;
    }
}