package com.school_circle.ssm.model;

import com.school_circle.ssm.utils.VerifyCode;

import java.util.Date;

public class ScVerifyCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_verify_code.code_id
     *
     * @mbggenerated Tue Apr 25 17:16:06 CST 2017
     */
    private String codeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_verify_code.code_string
     *
     * @mbggenerated Tue Apr 25 17:16:06 CST 2017
     */
    private String codeString;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc_verify_code.code_create_on
     *
     * @mbggenerated Tue Apr 25 17:16:06 CST 2017
     */
    private Date codeCreateOn;

    public ScVerifyCode(VerifyCode verifyCode) {
        this.setCodeId(verifyCode.getVerifyCodeUrl());
        this.setCodeString(verifyCode.getVerifyCode());
        this.setCodeCreateOn(new Date());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_verify_code.code_id
     *
     * @return the value of sc_verify_code.code_id
     *
     * @mbggenerated Tue Apr 25 17:16:06 CST 2017
     */
    public String getCodeId() {
        return codeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_verify_code.code_id
     *
     * @param codeId the value for sc_verify_code.code_id
     *
     * @mbggenerated Tue Apr 25 17:16:06 CST 2017
     */
    public void setCodeId(String codeId) {
        this.codeId = codeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_verify_code.code_string
     *
     * @return the value of sc_verify_code.code_string
     *
     * @mbggenerated Tue Apr 25 17:16:06 CST 2017
     */
    public String getCodeString() {
        return codeString;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_verify_code.code_string
     *
     * @param codeString the value for sc_verify_code.code_string
     *
     * @mbggenerated Tue Apr 25 17:16:06 CST 2017
     */
    public void setCodeString(String codeString) {
        this.codeString = codeString;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc_verify_code.code_create_on
     *
     * @return the value of sc_verify_code.code_create_on
     *
     * @mbggenerated Tue Apr 25 17:16:06 CST 2017
     */
    public Date getCodeCreateOn() {
        return codeCreateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc_verify_code.code_create_on
     *
     * @param codeCreateOn the value for sc_verify_code.code_create_on
     *
     * @mbggenerated Tue Apr 25 17:16:06 CST 2017
     */
    public void setCodeCreateOn(Date codeCreateOn) {
        this.codeCreateOn = codeCreateOn;
    }
}