package com.school_circle.ssm.mapper;

import com.school_circle.ssm.model.ScLogin;
import java.util.List;

public interface ScLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_login
     *
     * @mbggenerated Thu May 04 14:20:52 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_login
     *
     * @mbggenerated Thu May 04 14:20:52 CST 2017
     */
    int insert(ScLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_login
     *
     * @mbggenerated Thu May 04 14:20:52 CST 2017
     */
    ScLogin selectByPrimaryKey(Long id);

    ScLogin selectByToken(String token);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_login
     *
     * @mbggenerated Thu May 04 14:20:52 CST 2017
     */
    List<ScLogin> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_login
     *
     * @mbggenerated Thu May 04 14:20:52 CST 2017
     */
    int updateByPrimaryKey(ScLogin record);
}