package com.school_circle.ssm.mapper;

import com.school_circle.ssm.model.ScMultipartFile;
import java.util.List;

public interface ScMultipartFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_multipart_file
     *
     * @mbggenerated Wed Apr 26 15:21:13 CST 2017
     */
    int deleteByPrimaryKey(String multipartId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_multipart_file
     *
     * @mbggenerated Wed Apr 26 15:21:13 CST 2017
     */
    int insert(ScMultipartFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_multipart_file
     *
     * @mbggenerated Wed Apr 26 15:21:13 CST 2017
     */
    ScMultipartFile selectByPrimaryKey(String multipartId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_multipart_file
     *
     * @mbggenerated Wed Apr 26 15:21:13 CST 2017
     */
    List<ScMultipartFile> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_multipart_file
     *
     * @mbggenerated Wed Apr 26 15:21:13 CST 2017
     */
    int updateByPrimaryKey(ScMultipartFile record);

    int insertByBatch(List<ScMultipartFile> records);
}