package com.school_circle.ssm.mapper;

import com.school_circle.ssm.model.ScPost;
import java.util.List;

public interface ScPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_post
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_post
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    int insert(ScPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_post
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    ScPost selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_post
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    List<ScPost> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_post
     *
     * @mbggenerated Wed Apr 26 15:17:25 CST 2017
     */
    int updateByPrimaryKey(ScPost record);

    List<ScPost> selectPostListByType(String postType);
}