package com.school_circle.ssm.mapper;

import com.school_circle.ssm.model.ScPost;
import com.school_circle.ssm.model.ScReply;
import java.util.List;

public interface ScReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_reply
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    int deleteByPrimaryKey(String id);

    int deleteByPostId(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_reply
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    int insert(ScReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_reply
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    ScReply selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_reply
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    List<ScReply> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_reply
     *
     * @mbggenerated Wed Apr 26 15:34:31 CST 2017
     */
    int updateByPrimaryKey(ScReply record);

    List<ScReply> selectReplyListByRootPostId(String rootPostId);

    List<ScReply> selectReplyListByParentPostId(String parentPostId);
}