package com.school_circle.ssm.mapper;

import com.school_circle.ssm.model.ScUserMessage;
import com.school_circle.ssm.model.UserMessageItem;

import java.util.List;

public interface ScUserMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user_message
     *
     * @mbggenerated Fri Mar 24 16:44:25 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    List<UserMessageItem> selectListByUserId(long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user_message
     *
     * @mbggenerated Fri Mar 24 16:44:25 CST 2017
     */
    int insert(ScUserMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user_message
     *
     * @mbggenerated Fri Mar 24 16:44:25 CST 2017
     */
    ScUserMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user_message
     *
     * @mbggenerated Fri Mar 24 16:44:25 CST 2017
     */
    List<ScUserMessage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user_message
     *
     * @mbggenerated Fri Mar 24 16:44:25 CST 2017
     */
    int updateByPrimaryKey(ScUserMessage record);

    List<ScUserMessage> selectByUserId(long fromId,long toId);
}