package com.school_circle.ssm.mapper;

import com.school_circle.ssm.model.ScUserUnreadMessage;
import com.school_circle.ssm.model.UserMessageItem;

import java.util.List;

public interface ScUserUnreadMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user_unread_message
     *
     * @mbggenerated Fri Mar 24 16:44:38 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user_unread_message
     *
     * @mbggenerated Fri Mar 24 16:44:38 CST 2017
     */
    int insert(ScUserUnreadMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user_unread_message
     *
     * @mbggenerated Fri Mar 24 16:44:38 CST 2017
     */
    ScUserUnreadMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user_unread_message
     *
     * @mbggenerated Fri Mar 24 16:44:38 CST 2017
     */
    List<ScUserUnreadMessage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_user_unread_message
     *
     * @mbggenerated Fri Mar 24 16:44:38 CST 2017
     */
    int updateByPrimaryKey(ScUserUnreadMessage record);

    ScUserUnreadMessage selectByUserId(long userId,long fromId);

}