package com.school_circle.ssm.mapper;

import com.school_circle.ssm.model.ScVerifyCode;
import java.util.List;

public interface ScVerifyCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_verify_code
     *
     * @mbggenerated Tue Apr 25 17:16:06 CST 2017
     */
    int deleteByPrimaryKey(String codeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_verify_code
     *
     * @mbggenerated Tue Apr 25 17:16:06 CST 2017
     */
    int insert(ScVerifyCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_verify_code
     *
     * @mbggenerated Tue Apr 25 17:16:06 CST 2017
     */
    ScVerifyCode selectByPrimaryKey(String codeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_verify_code
     *
     * @mbggenerated Tue Apr 25 17:16:06 CST 2017
     */
    List<ScVerifyCode> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_verify_code
     *
     * @mbggenerated Tue Apr 25 17:16:06 CST 2017
     */
    int updateByPrimaryKey(ScVerifyCode record);
}